// Command genfixture regenerates the Phase 0 compatibility fixtures for
// the P1-01 backward-compatibility tests.
//
// Usage (from the ir/v1 package directory):
//
//	go run ./testdata/genfixture
//
// The fixtures document the pre-generation_plan state of the IR contract.
// They are intentionally generated without a GenerationPlan: they must be
// readable by Phase 1 types with the plan absent. The binary bytes are
// identical whether generated by the Phase 0 or Phase 1 schema, because an
// absent plan contributes no bytes; the JSON contract is defined by parse
// result, not raw bytes (protojson varies whitespace per binary build).
// These files were first committed while the Phase 0 schema was current.
//
// Do not run this command to absorb unrelated IR changes into the fixture
// without reviewing the resulting diff.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	observabilityv1 "github.com/zhuyanxi/axiom-insight/ir/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

func main() {
	document := phase0Document()

	binary, err := proto.MarshalOptions{Deterministic: true}.Marshal(document)
	if err != nil {
		fatal("marshal binary fixture: %v", err)
	}
	json, err := protojson.MarshalOptions{UseProtoNames: true, Indent: "  "}.Marshal(document)
	if err != nil {
		fatal("marshal JSON fixture: %v", err)
	}

	// Resolve the fixture directory from this source file so the command
	// works from any working directory.
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal("locate generator source file")
	}
	outDir := filepath.Join(filepath.Dir(sourceFile), "..")
	for name, contents := range map[string][]byte{
		"phase0-document.bin":  binary,
		"phase0-document.json": append(json, '\n'),
	} {
		target := filepath.Join(outDir, name)
		if err := os.WriteFile(target, contents, 0o644); err != nil {
			fatal("write %s: %v", target, err)
		}
		fmt.Printf("wrote %s\n", target)
	}
}

// phase0Document builds the same document the Phase 0 analyzer would emit:
// no GenerationPlan, one service, one package, two functions, endpoints of
// every supported kind, dependencies of every supported kind and one call
// edge.
func phase0Document() *observabilityv1.ObservabilityDocument {
	return &observabilityv1.ObservabilityDocument{
		SchemaVersion: "v1",
		Service: &observabilityv1.Service{
			Name:       "orders",
			SourceRoot: "./",
			Language:   "go",
			ModulePath: "example.com/orders",
			Version:    "1.0.0",
			PackageIds: []string{"pkg:orders"},
		},
		Packages: []*observabilityv1.Package{{
			Id:         "pkg:orders",
			Name:       "orders",
			ImportPath: "example.com/orders",
			Files:      []string{"handler.go", "store.go"},
		}},
		Functions: []*observabilityv1.Function{
			{
				Id:            "fn:orders.CreateOrder",
				Name:          "CreateOrder",
				QualifiedName: "orders.CreateOrder",
				PackageId:     "pkg:orders",
				PackagePath:   "example.com/orders",
				Receiver:      "Orders",
				Signature:     "func() error",
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "handler.go",
					StartLine:    10,
					StartColumn:  1,
					EndLine:      12,
					EndColumn:    2,
				},
				Exported:          true,
				InputEndpointIds:  []string{"endpoint:http:create-order", "endpoint:grpc:create-order", "endpoint:cron:cleanup"},
				DependencyIds:     []string{"dependency:redis", "dependency:sql"},
				CalleeFunctionIds: []string{"fn:orders.StoreOrder"},
			},
			{
				Id:            "fn:orders.StoreOrder",
				Name:          "StoreOrder",
				QualifiedName: "orders.StoreOrder",
				PackageId:     "pkg:orders",
				PackagePath:   "example.com/orders",
				Signature:     "func() error",
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "store.go",
					StartLine:    3,
					StartColumn:  1,
					EndLine:      9,
					EndColumn:    2,
				},
				Exported:          true,
				CallerFunctionIds: []string{"fn:orders.CreateOrder"},
				InputEndpointIds:  []string{"endpoint:cron:cleanup"},
				DependencyIds:     []string{"dependency:sql"},
				OutputEndpointIds: []string{"endpoint:cron:cleanup"},
			},
		},
		Endpoints: []*observabilityv1.Endpoint{
			{
				Id:         "endpoint:http:create-order",
				Kind:       observabilityv1.EndpointKind_HTTP_HANDLER,
				Name:       "CreateOrder",
				FunctionId: "fn:orders.CreateOrder",
				HttpMethod: "POST",
				HttpPath:   "/orders",
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "handler.go",
					StartLine:    11,
					StartColumn:  2,
					EndLine:      11,
					EndColumn:    33,
				},
			},
			{
				Id:          "endpoint:grpc:create-order",
				Kind:        observabilityv1.EndpointKind_GRPC_HANDLER,
				Name:        "CreateOrder",
				FunctionId:  "fn:orders.CreateOrder",
				GrpcService: "orders.OrderService",
				GrpcMethod:  "CreateOrder",
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "handler.go",
					StartLine:    15,
					StartColumn:  2,
					EndLine:      15,
					EndColumn:    60,
				},
			},
			{
				Id:           "endpoint:cron:cleanup",
				Kind:         observabilityv1.EndpointKind_CRON_JOB,
				Name:         "cleanup",
				FunctionId:   "fn:orders.StoreOrder",
				CronSchedule: "0 3 * * *",
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "store.go",
					StartLine:    5,
					StartColumn:  2,
					EndLine:      5,
					EndColumn:    31,
				},
			},
		},
		Dependencies: []*observabilityv1.Dependency{
			{
				Id:            "dependency:redis",
				Kind:          observabilityv1.DependencyKind_REDIS,
				Name:          "redis.Client.Get",
				FunctionId:    "fn:orders.CreateOrder",
				Operation:     "get",
				TargetPackage: "github.com/redis/go-redis/v9",
				Resource:      "orders",
				Value:         "order:{id}",
				ValueIsStatic: true,
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "handler.go",
					StartLine:    12,
					StartColumn:  3,
					EndLine:      12,
					EndColumn:    44,
				},
			},
			{
				Id:            "dependency:sql",
				Kind:          observabilityv1.DependencyKind_SQL,
				Name:          "database/sql.Query",
				FunctionId:    "fn:orders.StoreOrder",
				Operation:     "query",
				TargetPackage: "database/sql",
				Resource:      "orders",
				Value:         "INSERT INTO orders (id) VALUES (?)",
				ValueIsStatic: true,
				SourceLocation: &observabilityv1.SourceLocation{
					RelativePath: "store.go",
					StartLine:    6,
					StartColumn:  3,
					EndLine:      6,
					EndColumn:    62,
				},
			},
		},
		CallEdges: []*observabilityv1.CallEdge{{
			Id:               "edge:create-order-store",
			CallerFunctionId: "fn:orders.CreateOrder",
			CalleeFunctionId: "fn:orders.StoreOrder",
			Resolution:       observabilityv1.CallResolution_RESOLVED,
			SourceLocation: &observabilityv1.SourceLocation{
				RelativePath: "handler.go",
				StartLine:    13,
				StartColumn:  3,
				EndLine:      13,
				EndColumn:    31,
			},
		}},
		Diagnostics: []*observabilityv1.Diagnostic{
			{
				Severity: observabilityv1.DiagnosticSeverity_WARNING,
				Code:     "UNRESOLVED_CALL",
				Message:  "interface call target could not be resolved",
			},
			{
				Severity: observabilityv1.DiagnosticSeverity_INFO,
				Code:     "DYNAMIC_REDIS_KEY",
				Message:  "redis key is dynamic",
			},
		},
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genfixture: "+format+"\n", args...)
	os.Exit(1)
}
