package semantic

const (
	DiagnosticCodeConfigReadError         = "CONFIG_READ_ERROR"
	DiagnosticCodeInvalidConfig           = "INVALID_CONFIG"
	DiagnosticCodeGoParseError            = "GO_PARSE_ERROR"
	DiagnosticCodePackageLoadError        = "PACKAGE_LOAD_ERROR"
	DiagnosticCodeUnresolvedCall          = "UNRESOLVED_CALL"
	DiagnosticCodeDynamicCronSchedule     = "DYNAMIC_CRON_SCHEDULE"
	DiagnosticCodeDynamicGRPCTarget       = "DYNAMIC_GRPC_TARGET"
	DiagnosticCodeDynamicHTTPMethod       = "DYNAMIC_HTTP_METHOD"
	DiagnosticCodeDynamicHTTPPattern      = "DYNAMIC_HTTP_PATTERN"
	DiagnosticCodeDynamicHTTPURL          = "DYNAMIC_HTTP_URL"
	DiagnosticCodeDynamicKafkaValue       = "DYNAMIC_KAFKA_VALUE"
	DiagnosticCodeDynamicRedisKey         = "DYNAMIC_REDIS_KEY"
	DiagnosticCodeDynamicSQL              = "DYNAMIC_SQL"
	DiagnosticCodeInvalidHTTPClientCall   = "INVALID_HTTP_CLIENT_CALL"
	DiagnosticCodeMissingSQLQuery         = "MISSING_SQL_QUERY"
	DiagnosticCodeInvalidCronRegistration = "INVALID_CRON_REGISTRATION"
	DiagnosticCodeInvalidGRPCRegistration = "INVALID_GRPC_REGISTRATION"
	DiagnosticCodeInvalidHTTPRegistration = "INVALID_HTTP_REGISTRATION"
	DiagnosticCodeUnresolvedCronCallback  = "UNRESOLVED_CRON_CALLBACK"
	DiagnosticCodeUnresolvedGRPCMethod    = "UNRESOLVED_GRPC_METHOD"
	DiagnosticCodeUnresolvedGRPCServer    = "UNRESOLVED_GRPC_SERVER"
	DiagnosticCodeUnresolvedHTTPHandler   = "UNRESOLVED_HTTP_HANDLER"
	DiagnosticCodeUnsupportedHTTPRouter   = "UNSUPPORTED_HTTP_ROUTER"
	DiagnosticCodeInvalidSourcePath       = "INVALID_SOURCE_PATH"
	DiagnosticCodeMissingSourceLocation   = "MISSING_SOURCE_LOCATION"
	DiagnosticCodeUnknownCallResolution   = "UNKNOWN_CALL_RESOLUTION"
	DiagnosticCodeUnknownDependencyKind   = "UNKNOWN_DEPENDENCY_KIND"
	DiagnosticCodeUnknownEndpointKind     = "UNKNOWN_ENDPOINT_KIND"
)
