// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ir/v1/generation.proto

package observabilityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType identifies the supported instrument types.
type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED MetricType = 0
	MetricType_METRIC_TYPE_COUNTER     MetricType = 1
	MetricType_METRIC_TYPE_HISTOGRAM   MetricType = 2
	MetricType_METRIC_TYPE_GAUGE       MetricType = 3
	MetricType_METRIC_TYPE_SUMMARY     MetricType = 4
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "METRIC_TYPE_UNSPECIFIED",
		1: "METRIC_TYPE_COUNTER",
		2: "METRIC_TYPE_HISTOGRAM",
		3: "METRIC_TYPE_GAUGE",
		4: "METRIC_TYPE_SUMMARY",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED": 0,
		"METRIC_TYPE_COUNTER":     1,
		"METRIC_TYPE_HISTOGRAM":   2,
		"METRIC_TYPE_GAUGE":       3,
		"METRIC_TYPE_SUMMARY":     4,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{0}
}

// SpanKind mirrors OpenTelemetry span kinds by name only; it does not
// expose any SDK type.
type SpanKind int32

const (
	SpanKind_SPAN_KIND_UNSPECIFIED SpanKind = 0
	SpanKind_SPAN_KIND_SERVER      SpanKind = 1
	SpanKind_SPAN_KIND_CLIENT      SpanKind = 2
	SpanKind_SPAN_KIND_PRODUCER    SpanKind = 3
	SpanKind_SPAN_KIND_CONSUMER    SpanKind = 4
	SpanKind_SPAN_KIND_INTERNAL    SpanKind = 5
)

// Enum value maps for SpanKind.
var (
	SpanKind_name = map[int32]string{
		0: "SPAN_KIND_UNSPECIFIED",
		1: "SPAN_KIND_SERVER",
		2: "SPAN_KIND_CLIENT",
		3: "SPAN_KIND_PRODUCER",
		4: "SPAN_KIND_CONSUMER",
		5: "SPAN_KIND_INTERNAL",
	}
	SpanKind_value = map[string]int32{
		"SPAN_KIND_UNSPECIFIED": 0,
		"SPAN_KIND_SERVER":      1,
		"SPAN_KIND_CLIENT":      2,
		"SPAN_KIND_PRODUCER":    3,
		"SPAN_KIND_CONSUMER":    4,
		"SPAN_KIND_INTERNAL":    5,
	}
)

func (x SpanKind) Enum() *SpanKind {
	p := new(SpanKind)
	*p = x
	return p
}

func (x SpanKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[1].Descriptor()
}

func (SpanKind) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[1]
}

func (x SpanKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanKind.Descriptor instead.
func (SpanKind) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{1}
}

// TargetKind identifies which IR entity a plan item references.
type TargetKind int32

const (
	TargetKind_TARGET_KIND_UNSPECIFIED TargetKind = 0
	TargetKind_TARGET_KIND_ENDPOINT    TargetKind = 1
	TargetKind_TARGET_KIND_FUNCTION    TargetKind = 2
	TargetKind_TARGET_KIND_DEPENDENCY  TargetKind = 3
	TargetKind_TARGET_KIND_CALL_EDGE   TargetKind = 4
)

// Enum value maps for TargetKind.
var (
	TargetKind_name = map[int32]string{
		0: "TARGET_KIND_UNSPECIFIED",
		1: "TARGET_KIND_ENDPOINT",
		2: "TARGET_KIND_FUNCTION",
		3: "TARGET_KIND_DEPENDENCY",
		4: "TARGET_KIND_CALL_EDGE",
	}
	TargetKind_value = map[string]int32{
		"TARGET_KIND_UNSPECIFIED": 0,
		"TARGET_KIND_ENDPOINT":    1,
		"TARGET_KIND_FUNCTION":    2,
		"TARGET_KIND_DEPENDENCY":  3,
		"TARGET_KIND_CALL_EDGE":   4,
	}
)

func (x TargetKind) Enum() *TargetKind {
	p := new(TargetKind)
	*p = x
	return p
}

func (x TargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[2].Descriptor()
}

func (TargetKind) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[2]
}

func (x TargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetKind.Descriptor instead.
func (TargetKind) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{2}
}

// TriggerPhase identifies the moment a signal is recorded.
type TriggerPhase int32

const (
	TriggerPhase_TRIGGER_PHASE_UNSPECIFIED TriggerPhase = 0
	// START fires when the operation begins.
	TriggerPhase_TRIGGER_PHASE_START TriggerPhase = 1
	// END fires when the operation completes, success or failure.
	TriggerPhase_TRIGGER_PHASE_END TriggerPhase = 2
	// STATE_CHANGE fires whenever the observed state changes.
	TriggerPhase_TRIGGER_PHASE_STATE_CHANGE TriggerPhase = 3
)

// Enum value maps for TriggerPhase.
var (
	TriggerPhase_name = map[int32]string{
		0: "TRIGGER_PHASE_UNSPECIFIED",
		1: "TRIGGER_PHASE_START",
		2: "TRIGGER_PHASE_END",
		3: "TRIGGER_PHASE_STATE_CHANGE",
	}
	TriggerPhase_value = map[string]int32{
		"TRIGGER_PHASE_UNSPECIFIED":  0,
		"TRIGGER_PHASE_START":        1,
		"TRIGGER_PHASE_END":          2,
		"TRIGGER_PHASE_STATE_CHANGE": 3,
	}
)

func (x TriggerPhase) Enum() *TriggerPhase {
	p := new(TriggerPhase)
	*p = x
	return p
}

func (x TriggerPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[3].Descriptor()
}

func (TriggerPhase) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[3]
}

func (x TriggerPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerPhase.Descriptor instead.
func (TriggerPhase) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{3}
}

// ValueSource classifies where a bound value comes from.
type ValueSource int32

const (
	ValueSource_VALUE_SOURCE_UNSPECIFIED ValueSource = 0
	// PLAN_CONSTANT: constant fixed by the Generator, e.g. a counter value of
	// "1" or an operation normalized from a validated IR field.
	ValueSource_VALUE_SOURCE_PLAN_CONSTANT ValueSource = 1
	// IR_CONSTANT: constant copied from a validated IR field, e.g.
	// "service.name" or "endpoint.http_path".
	ValueSource_VALUE_SOURCE_IR_CONSTANT ValueSource = 2
	// RUNTIME_RESOURCE: value bound at runtime from resource information,
	// e.g. "runtime.resource.service.version".
	ValueSource_VALUE_SOURCE_RUNTIME_RESOURCE ValueSource = 3
	// RUNTIME_CONTEXT: value bound at runtime from request context, e.g.
	// "runtime.context.trace_id".
	ValueSource_VALUE_SOURCE_RUNTIME_CONTEXT ValueSource = 4
	// RUNTIME_RESULT: value bound at runtime from the operation result, e.g.
	// "runtime.operation.status" or "runtime.operation.duration_seconds".
	ValueSource_VALUE_SOURCE_RUNTIME_RESULT ValueSource = 5
)

// Enum value maps for ValueSource.
var (
	ValueSource_name = map[int32]string{
		0: "VALUE_SOURCE_UNSPECIFIED",
		1: "VALUE_SOURCE_PLAN_CONSTANT",
		2: "VALUE_SOURCE_IR_CONSTANT",
		3: "VALUE_SOURCE_RUNTIME_RESOURCE",
		4: "VALUE_SOURCE_RUNTIME_CONTEXT",
		5: "VALUE_SOURCE_RUNTIME_RESULT",
	}
	ValueSource_value = map[string]int32{
		"VALUE_SOURCE_UNSPECIFIED":      0,
		"VALUE_SOURCE_PLAN_CONSTANT":    1,
		"VALUE_SOURCE_IR_CONSTANT":      2,
		"VALUE_SOURCE_RUNTIME_RESOURCE": 3,
		"VALUE_SOURCE_RUNTIME_CONTEXT":  4,
		"VALUE_SOURCE_RUNTIME_RESULT":   5,
	}
)

func (x ValueSource) Enum() *ValueSource {
	p := new(ValueSource)
	*p = x
	return p
}

func (x ValueSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueSource) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[4].Descriptor()
}

func (ValueSource) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[4]
}

func (x ValueSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueSource.Descriptor instead.
func (ValueSource) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{4}
}

// ValueType is the data type of a bound value.
type ValueType int32

const (
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	ValueType_VALUE_TYPE_STRING      ValueType = 1
	ValueType_VALUE_TYPE_INT64       ValueType = 2
	ValueType_VALUE_TYPE_DOUBLE      ValueType = 3
	ValueType_VALUE_TYPE_BOOL        ValueType = 4
	// STATUS is the finite runtime operation status vocabulary.
	ValueType_VALUE_TYPE_STATUS ValueType = 5
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNSPECIFIED",
		1: "VALUE_TYPE_STRING",
		2: "VALUE_TYPE_INT64",
		3: "VALUE_TYPE_DOUBLE",
		4: "VALUE_TYPE_BOOL",
		5: "VALUE_TYPE_STATUS",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"VALUE_TYPE_STRING":      1,
		"VALUE_TYPE_INT64":       2,
		"VALUE_TYPE_DOUBLE":      3,
		"VALUE_TYPE_BOOL":        4,
		"VALUE_TYPE_STATUS":      5,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[5].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[5]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{5}
}

// CardinalityClass estimates how many distinct values a binding may take.
type CardinalityClass int32

const (
	CardinalityClass_CARDINALITY_CLASS_UNSPECIFIED CardinalityClass = 0
	// CONSTANT: one value for the whole plan.
	CardinalityClass_CARDINALITY_CLASS_CONSTANT CardinalityClass = 1
	// LOW: bounded low-cardinality values.
	CardinalityClass_CARDINALITY_CLASS_LOW CardinalityClass = 2
	// HIGH: unbounded values; must not become metric attributes.
	CardinalityClass_CARDINALITY_CLASS_HIGH CardinalityClass = 3
)

// Enum value maps for CardinalityClass.
var (
	CardinalityClass_name = map[int32]string{
		0: "CARDINALITY_CLASS_UNSPECIFIED",
		1: "CARDINALITY_CLASS_CONSTANT",
		2: "CARDINALITY_CLASS_LOW",
		3: "CARDINALITY_CLASS_HIGH",
	}
	CardinalityClass_value = map[string]int32{
		"CARDINALITY_CLASS_UNSPECIFIED": 0,
		"CARDINALITY_CLASS_CONSTANT":    1,
		"CARDINALITY_CLASS_LOW":         2,
		"CARDINALITY_CLASS_HIGH":        3,
	}
)

func (x CardinalityClass) Enum() *CardinalityClass {
	p := new(CardinalityClass)
	*p = x
	return p
}

func (x CardinalityClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardinalityClass) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[6].Descriptor()
}

func (CardinalityClass) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[6]
}

func (x CardinalityClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardinalityClass.Descriptor instead.
func (CardinalityClass) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{6}
}

// ParentStrategyMode chooses how a parent span is established.
type ParentStrategyMode int32

const (
	ParentStrategyMode_PARENT_STRATEGY_MODE_UNSPECIFIED ParentStrategyMode = 0
	// EXTRACT_OR_ROOT: extract a remote parent from the carrier when present,
	// otherwise start a new root.
	ParentStrategyMode_PARENT_STRATEGY_MODE_EXTRACT_OR_ROOT ParentStrategyMode = 1
	// NEW_ROOT: always start a new root unless the Runtime explicitly
	// supplies a context.
	ParentStrategyMode_PARENT_STRATEGY_MODE_NEW_ROOT ParentStrategyMode = 2
	// CURRENT_CONTEXT: use the current execution context as parent.
	ParentStrategyMode_PARENT_STRATEGY_MODE_CURRENT_CONTEXT ParentStrategyMode = 3
	// STATIC: always parent to the referenced SpanPlan.
	ParentStrategyMode_PARENT_STRATEGY_MODE_STATIC ParentStrategyMode = 4
)

// Enum value maps for ParentStrategyMode.
var (
	ParentStrategyMode_name = map[int32]string{
		0: "PARENT_STRATEGY_MODE_UNSPECIFIED",
		1: "PARENT_STRATEGY_MODE_EXTRACT_OR_ROOT",
		2: "PARENT_STRATEGY_MODE_NEW_ROOT",
		3: "PARENT_STRATEGY_MODE_CURRENT_CONTEXT",
		4: "PARENT_STRATEGY_MODE_STATIC",
	}
	ParentStrategyMode_value = map[string]int32{
		"PARENT_STRATEGY_MODE_UNSPECIFIED":     0,
		"PARENT_STRATEGY_MODE_EXTRACT_OR_ROOT": 1,
		"PARENT_STRATEGY_MODE_NEW_ROOT":        2,
		"PARENT_STRATEGY_MODE_CURRENT_CONTEXT": 3,
		"PARENT_STRATEGY_MODE_STATIC":          4,
	}
)

func (x ParentStrategyMode) Enum() *ParentStrategyMode {
	p := new(ParentStrategyMode)
	*p = x
	return p
}

func (x ParentStrategyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParentStrategyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[7].Descriptor()
}

func (ParentStrategyMode) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[7]
}

func (x ParentStrategyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParentStrategyMode.Descriptor instead.
func (ParentStrategyMode) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{7}
}

// StatusSetting is an OTel-compatible span status output.
type StatusSetting int32

const (
	StatusSetting_STATUS_SETTING_UNSPECIFIED StatusSetting = 0
	StatusSetting_STATUS_SETTING_UNSET       StatusSetting = 1
	StatusSetting_STATUS_SETTING_ERROR       StatusSetting = 2
	StatusSetting_STATUS_SETTING_OK          StatusSetting = 3
)

// Enum value maps for StatusSetting.
var (
	StatusSetting_name = map[int32]string{
		0: "STATUS_SETTING_UNSPECIFIED",
		1: "STATUS_SETTING_UNSET",
		2: "STATUS_SETTING_ERROR",
		3: "STATUS_SETTING_OK",
	}
	StatusSetting_value = map[string]int32{
		"STATUS_SETTING_UNSPECIFIED": 0,
		"STATUS_SETTING_UNSET":       1,
		"STATUS_SETTING_ERROR":       2,
		"STATUS_SETTING_OK":          3,
	}
)

func (x StatusSetting) Enum() *StatusSetting {
	p := new(StatusSetting)
	*p = x
	return p
}

func (x StatusSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[8].Descriptor()
}

func (StatusSetting) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[8]
}

func (x StatusSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusSetting.Descriptor instead.
func (StatusSetting) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{8}
}

// RuntimeStatus is the finite runtime operation status vocabulary.
type RuntimeStatus int32

const (
	RuntimeStatus_RUNTIME_STATUS_UNSPECIFIED RuntimeStatus = 0
	RuntimeStatus_RUNTIME_STATUS_OK          RuntimeStatus = 1
	RuntimeStatus_RUNTIME_STATUS_ERROR       RuntimeStatus = 2
	RuntimeStatus_RUNTIME_STATUS_CANCELLED   RuntimeStatus = 3
	RuntimeStatus_RUNTIME_STATUS_TIMEOUT     RuntimeStatus = 4
	RuntimeStatus_RUNTIME_STATUS_UNKNOWN     RuntimeStatus = 5
)

// Enum value maps for RuntimeStatus.
var (
	RuntimeStatus_name = map[int32]string{
		0: "RUNTIME_STATUS_UNSPECIFIED",
		1: "RUNTIME_STATUS_OK",
		2: "RUNTIME_STATUS_ERROR",
		3: "RUNTIME_STATUS_CANCELLED",
		4: "RUNTIME_STATUS_TIMEOUT",
		5: "RUNTIME_STATUS_UNKNOWN",
	}
	RuntimeStatus_value = map[string]int32{
		"RUNTIME_STATUS_UNSPECIFIED": 0,
		"RUNTIME_STATUS_OK":          1,
		"RUNTIME_STATUS_ERROR":       2,
		"RUNTIME_STATUS_CANCELLED":   3,
		"RUNTIME_STATUS_TIMEOUT":     4,
		"RUNTIME_STATUS_UNKNOWN":     5,
	}
)

func (x RuntimeStatus) Enum() *RuntimeStatus {
	p := new(RuntimeStatus)
	*p = x
	return p
}

func (x RuntimeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[9].Descriptor()
}

func (RuntimeStatus) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[9]
}

func (x RuntimeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeStatus.Descriptor instead.
func (RuntimeStatus) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{9}
}

// LogSeverity is the structured log severity vocabulary.
type LogSeverity int32

const (
	LogSeverity_LOG_SEVERITY_UNSPECIFIED LogSeverity = 0
	LogSeverity_LOG_SEVERITY_INFO        LogSeverity = 1
	LogSeverity_LOG_SEVERITY_WARN        LogSeverity = 2
	LogSeverity_LOG_SEVERITY_ERROR       LogSeverity = 3
)

// Enum value maps for LogSeverity.
var (
	LogSeverity_name = map[int32]string{
		0: "LOG_SEVERITY_UNSPECIFIED",
		1: "LOG_SEVERITY_INFO",
		2: "LOG_SEVERITY_WARN",
		3: "LOG_SEVERITY_ERROR",
	}
	LogSeverity_value = map[string]int32{
		"LOG_SEVERITY_UNSPECIFIED": 0,
		"LOG_SEVERITY_INFO":        1,
		"LOG_SEVERITY_WARN":        2,
		"LOG_SEVERITY_ERROR":       3,
	}
)

func (x LogSeverity) Enum() *LogSeverity {
	p := new(LogSeverity)
	*p = x
	return p
}

func (x LogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[10].Descriptor()
}

func (LogSeverity) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[10]
}

func (x LogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSeverity.Descriptor instead.
func (LogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{10}
}

// PlanSeverity is the generator diagnostic severity vocabulary.
type PlanSeverity int32

const (
	PlanSeverity_PLAN_SEVERITY_UNSPECIFIED PlanSeverity = 0
	PlanSeverity_PLAN_SEVERITY_INFO        PlanSeverity = 1
	PlanSeverity_PLAN_SEVERITY_WARNING     PlanSeverity = 2
	PlanSeverity_PLAN_SEVERITY_ERROR       PlanSeverity = 3
)

// Enum value maps for PlanSeverity.
var (
	PlanSeverity_name = map[int32]string{
		0: "PLAN_SEVERITY_UNSPECIFIED",
		1: "PLAN_SEVERITY_INFO",
		2: "PLAN_SEVERITY_WARNING",
		3: "PLAN_SEVERITY_ERROR",
	}
	PlanSeverity_value = map[string]int32{
		"PLAN_SEVERITY_UNSPECIFIED": 0,
		"PLAN_SEVERITY_INFO":        1,
		"PLAN_SEVERITY_WARNING":     2,
		"PLAN_SEVERITY_ERROR":       3,
	}
)

func (x PlanSeverity) Enum() *PlanSeverity {
	p := new(PlanSeverity)
	*p = x
	return p
}

func (x PlanSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_generation_proto_enumTypes[11].Descriptor()
}

func (PlanSeverity) Type() protoreflect.EnumType {
	return &file_ir_v1_generation_proto_enumTypes[11]
}

func (x PlanSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanSeverity.Descriptor instead.
func (PlanSeverity) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{11}
}

// GenerationPlan is the language-neutral, strongly typed output of the
// Generator Planner. It carries Metrics, Tracing and Logging definitions
// plus generator-owned diagnostics.
//
// Ownership boundary: this file is standalone (no imports), so the
// generator contract can evolve independently from the analysis IR.
// observability.proto imports this file one-way to append the optional
// generation_plan field. The Analyzer never constructs or fills a
// GenerationPlan; only the Generator Planner (Phase 1+) does. Adding,
// renaming or renumbering any published field requires a new explicit
// schema version; this contract is append-only.
type GenerationPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema_version is the GenerationPlan contract version. It evolves
	// independently from source_ir_schema_version.
	SchemaVersion string `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// source_ir_schema_version records the ObservabilityDocument schema
	// version this plan was derived from.
	SourceIrSchemaVersion string `protobuf:"bytes,2,opt,name=source_ir_schema_version,json=sourceIrSchemaVersion,proto3" json:"source_ir_schema_version,omitempty"`
	// service_name matches the source IR Service.name and is constant
	// across a single plan.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// metrics, spans and logs are ordered lists. Order is a presentation
	// detail; consumers must never rely on insertion order for semantics.
	Metrics       []*MetricPlan     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Spans         []*SpanPlan       `protobuf:"bytes,5,rep,name=spans,proto3" json:"spans,omitempty"`
	Logs          []*LogPlan        `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	Diagnostics   []*PlanDiagnostic `protobuf:"bytes,7,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationPlan) Reset() {
	*x = GenerationPlan{}
	mi := &file_ir_v1_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationPlan) ProtoMessage() {}

func (x *GenerationPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationPlan.ProtoReflect.Descriptor instead.
func (*GenerationPlan) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationPlan) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *GenerationPlan) GetSourceIrSchemaVersion() string {
	if x != nil {
		return x.SourceIrSchemaVersion
	}
	return ""
}

func (x *GenerationPlan) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GenerationPlan) GetMetrics() []*MetricPlan {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GenerationPlan) GetSpans() []*SpanPlan {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *GenerationPlan) GetLogs() []*LogPlan {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GenerationPlan) GetDiagnostics() []*PlanDiagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// MetricPlan defines one metric instrument and how to record it.
type MetricPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a stable, globally unique plan ID derived from signal, target
	// and purpose. It must not change when names change.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the normalized machine metric name (ASCII snake_case).
	Name string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type MetricType `protobuf:"varint,3,opt,name=type,proto3,enum=axiom.insight.ir.v1.MetricType" json:"type,omitempty"`
	// unit is a UCUM-compatible unit; empty means dimensionless.
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	// description explains the object, unit and record timing. It never
	// contains absolute paths or source snippets.
	Description string     `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Target      *TargetRef `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	// trigger describes when the instrument is recorded.
	Trigger *Trigger `protobuf:"bytes,7,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// value is the binding that produces the recorded value.
	Value      *ValueBinding       `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	Attributes []*AttributeBinding `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// function_id references the Function the target entity belongs to,
	// kept stable for Dashboard and Runtime consumers. Populated by the
	// Generator Planner for endpoint metrics; absent when the metric does
	// not belong to a function.
	FunctionId    string `protobuf:"bytes,10,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPlan) Reset() {
	*x = MetricPlan{}
	mi := &file_ir_v1_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPlan) ProtoMessage() {}

func (x *MetricPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPlan.ProtoReflect.Descriptor instead.
func (*MetricPlan) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{1}
}

func (x *MetricPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPlan) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *MetricPlan) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricPlan) GetTarget() *TargetRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MetricPlan) GetTrigger() *Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *MetricPlan) GetValue() *ValueBinding {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricPlan) GetAttributes() []*AttributeBinding {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *MetricPlan) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

// SpanPlan defines one span to be produced by the Runtime.
type SpanPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name follows the P1-04 naming rules (e.g. "POST /orders/{id}").
	Name         string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind         SpanKind            `protobuf:"varint,3,opt,name=kind,proto3,enum=axiom.insight.ir.v1.SpanKind" json:"kind,omitempty"`
	Target       *TargetRef          `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	StartTrigger *Trigger            `protobuf:"bytes,5,opt,name=start_trigger,json=startTrigger,proto3" json:"start_trigger,omitempty"`
	EndTrigger   *Trigger            `protobuf:"bytes,6,opt,name=end_trigger,json=endTrigger,proto3" json:"end_trigger,omitempty"`
	Parent       *ParentStrategy     `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Attributes   []*AttributeBinding `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// status maps every runtime operation status to an OTel-compatible
	// status; no status may be left unmapped.
	Status        *StatusPolicy `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Events        []*SpanEvent  `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanPlan) Reset() {
	*x = SpanPlan{}
	mi := &file_ir_v1_generation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanPlan) ProtoMessage() {}

func (x *SpanPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanPlan.ProtoReflect.Descriptor instead.
func (*SpanPlan) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{2}
}

func (x *SpanPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpanPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpanPlan) GetKind() SpanKind {
	if x != nil {
		return x.Kind
	}
	return SpanKind_SPAN_KIND_UNSPECIFIED
}

func (x *SpanPlan) GetTarget() *TargetRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SpanPlan) GetStartTrigger() *Trigger {
	if x != nil {
		return x.StartTrigger
	}
	return nil
}

func (x *SpanPlan) GetEndTrigger() *Trigger {
	if x != nil {
		return x.EndTrigger
	}
	return nil
}

func (x *SpanPlan) GetParent() *ParentStrategy {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *SpanPlan) GetAttributes() []*AttributeBinding {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SpanPlan) GetStatus() *StatusPolicy {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SpanPlan) GetEvents() []*SpanEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// LogPlan defines one structured log event.
type LogPlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// event_name is a lower-case dotted name, e.g. "http.request.completed".
	EventName string          `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Severity  LogSeverity     `protobuf:"varint,3,opt,name=severity,proto3,enum=axiom.insight.ir.v1.LogSeverity" json:"severity,omitempty"`
	Target    *TargetRef      `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Trigger   *Trigger        `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Fields    []*FieldBinding `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	// correlation_fields are stable field keys the Runtime must fill with
	// request/trace/span context when available. They never carry fake IDs.
	CorrelationFields []string `protobuf:"bytes,7,rep,name=correlation_fields,json=correlationFields,proto3" json:"correlation_fields,omitempty"`
	// redaction_policy_id selects a built-in redaction policy applied by the
	// Runtime; the Generator never inlines sensitive values.
	RedactionPolicyId string `protobuf:"bytes,8,opt,name=redaction_policy_id,json=redactionPolicyId,proto3" json:"redaction_policy_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogPlan) Reset() {
	*x = LogPlan{}
	mi := &file_ir_v1_generation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPlan) ProtoMessage() {}

func (x *LogPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPlan.ProtoReflect.Descriptor instead.
func (*LogPlan) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{3}
}

func (x *LogPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogPlan) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *LogPlan) GetSeverity() LogSeverity {
	if x != nil {
		return x.Severity
	}
	return LogSeverity_LOG_SEVERITY_UNSPECIFIED
}

func (x *LogPlan) GetTarget() *TargetRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *LogPlan) GetTrigger() *Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *LogPlan) GetFields() []*FieldBinding {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogPlan) GetCorrelationFields() []string {
	if x != nil {
		return x.CorrelationFields
	}
	return nil
}

func (x *LogPlan) GetRedactionPolicyId() string {
	if x != nil {
		return x.RedactionPolicyId
	}
	return ""
}

// TargetRef is a strongly typed reference to an IR entity. The target kind
// must match the ID's actual entity type or plan validation fails.
type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          TargetKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=axiom.insight.ir.v1.TargetKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_ir_v1_generation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{4}
}

func (x *TargetRef) GetKind() TargetKind {
	if x != nil {
		return x.Kind
	}
	return TargetKind_TARGET_KIND_UNSPECIFIED
}

func (x *TargetRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Trigger describes when a signal is recorded.
type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         TriggerPhase           `protobuf:"varint,1,opt,name=phase,proto3,enum=axiom.insight.ir.v1.TriggerPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_ir_v1_generation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{5}
}

func (x *Trigger) GetPhase() TriggerPhase {
	if x != nil {
		return x.Phase
	}
	return TriggerPhase_TRIGGER_PHASE_UNSPECIFIED
}

// ValueBinding states where a value comes from and how the Runtime must
// treat it. Plan constants, IR constants and runtime sources are kept
// distinct so no Renderer has to guess provenance.
type ValueBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the stable dotted source path, e.g. "runtime.operation.status"
	// or "endpoint.http_path".
	Path   string      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Source ValueSource `protobuf:"varint,2,opt,name=source,proto3,enum=axiom.insight.ir.v1.ValueSource" json:"source,omitempty"`
	Type   ValueType   `protobuf:"varint,3,opt,name=type,proto3,enum=axiom.insight.ir.v1.ValueType" json:"type,omitempty"`
	// required marks values the Runtime must provide. When false, a missing
	// runtime value falls back to fallback or the field is omitted.
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// fallback is a static fallback value; it must never contain secrets.
	Fallback      string           `protobuf:"bytes,5,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Cardinality   CardinalityClass `protobuf:"varint,6,opt,name=cardinality,proto3,enum=axiom.insight.ir.v1.CardinalityClass" json:"cardinality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueBinding) Reset() {
	*x = ValueBinding{}
	mi := &file_ir_v1_generation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueBinding) ProtoMessage() {}

func (x *ValueBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueBinding.ProtoReflect.Descriptor instead.
func (*ValueBinding) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{6}
}

func (x *ValueBinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValueBinding) GetSource() ValueSource {
	if x != nil {
		return x.Source
	}
	return ValueSource_VALUE_SOURCE_UNSPECIFIED
}

func (x *ValueBinding) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *ValueBinding) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ValueBinding) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *ValueBinding) GetCardinality() CardinalityClass {
	if x != nil {
		return x.Cardinality
	}
	return CardinalityClass_CARDINALITY_CLASS_UNSPECIFIED
}

// AttributeBinding binds one static metric or span attribute key to a value.
type AttributeBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ValueBinding          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeBinding) Reset() {
	*x = AttributeBinding{}
	mi := &file_ir_v1_generation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeBinding) ProtoMessage() {}

func (x *AttributeBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeBinding.ProtoReflect.Descriptor instead.
func (*AttributeBinding) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{7}
}

func (x *AttributeBinding) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeBinding) GetValue() *ValueBinding {
	if x != nil {
		return x.Value
	}
	return nil
}

// FieldBinding binds one structured log field key to a value.
type FieldBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ValueBinding          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldBinding) Reset() {
	*x = FieldBinding{}
	mi := &file_ir_v1_generation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldBinding) ProtoMessage() {}

func (x *FieldBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldBinding.ProtoReflect.Descriptor instead.
func (*FieldBinding) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{8}
}

func (x *FieldBinding) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldBinding) GetValue() *ValueBinding {
	if x != nil {
		return x.Value
	}
	return nil
}

// ParentStrategy decides how a span's parent is established at runtime.
type ParentStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  ParentStrategyMode     `protobuf:"varint,1,opt,name=mode,proto3,enum=axiom.insight.ir.v1.ParentStrategyMode" json:"mode,omitempty"`
	// static_parent_span_id is required when mode is STATIC and must
	// reference another SpanPlan id.
	StaticParentSpanId string `protobuf:"bytes,2,opt,name=static_parent_span_id,json=staticParentSpanId,proto3" json:"static_parent_span_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ParentStrategy) Reset() {
	*x = ParentStrategy{}
	mi := &file_ir_v1_generation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentStrategy) ProtoMessage() {}

func (x *ParentStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentStrategy.ProtoReflect.Descriptor instead.
func (*ParentStrategy) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{9}
}

func (x *ParentStrategy) GetMode() ParentStrategyMode {
	if x != nil {
		return x.Mode
	}
	return ParentStrategyMode_PARENT_STRATEGY_MODE_UNSPECIFIED
}

func (x *ParentStrategy) GetStaticParentSpanId() string {
	if x != nil {
		return x.StaticParentSpanId
	}
	return ""
}

// StatusPolicy maps each runtime operation status to a span status.
// Every runtime status must have exactly one documented mapping.
type StatusPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            StatusSetting          `protobuf:"varint,1,opt,name=ok,proto3,enum=axiom.insight.ir.v1.StatusSetting" json:"ok,omitempty"`
	Error         StatusSetting          `protobuf:"varint,2,opt,name=error,proto3,enum=axiom.insight.ir.v1.StatusSetting" json:"error,omitempty"`
	Timeout       StatusSetting          `protobuf:"varint,3,opt,name=timeout,proto3,enum=axiom.insight.ir.v1.StatusSetting" json:"timeout,omitempty"`
	Cancelled     StatusSetting          `protobuf:"varint,4,opt,name=cancelled,proto3,enum=axiom.insight.ir.v1.StatusSetting" json:"cancelled,omitempty"`
	Unknown       StatusSetting          `protobuf:"varint,5,opt,name=unknown,proto3,enum=axiom.insight.ir.v1.StatusSetting" json:"unknown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusPolicy) Reset() {
	*x = StatusPolicy{}
	mi := &file_ir_v1_generation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusPolicy) ProtoMessage() {}

func (x *StatusPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusPolicy.ProtoReflect.Descriptor instead.
func (*StatusPolicy) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{10}
}

func (x *StatusPolicy) GetOk() StatusSetting {
	if x != nil {
		return x.Ok
	}
	return StatusSetting_STATUS_SETTING_UNSPECIFIED
}

func (x *StatusPolicy) GetError() StatusSetting {
	if x != nil {
		return x.Error
	}
	return StatusSetting_STATUS_SETTING_UNSPECIFIED
}

func (x *StatusPolicy) GetTimeout() StatusSetting {
	if x != nil {
		return x.Timeout
	}
	return StatusSetting_STATUS_SETTING_UNSPECIFIED
}

func (x *StatusPolicy) GetCancelled() StatusSetting {
	if x != nil {
		return x.Cancelled
	}
	return StatusSetting_STATUS_SETTING_UNSPECIFIED
}

func (x *StatusPolicy) GetUnknown() StatusSetting {
	if x != nil {
		return x.Unknown
	}
	return StatusSetting_STATUS_SETTING_UNSPECIFIED
}

// SpanEvent defines a controlled event emitted by a span.
type SpanEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is a controlled static event name, e.g. "exception" or "timeout".
	// Raw error strings never become event names.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// statuses lists the runtime operation statuses that fire this event.
	// Empty means the event fires unconditionally.
	Statuses      []RuntimeStatus     `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=axiom.insight.ir.v1.RuntimeStatus" json:"statuses,omitempty"`
	Attributes    []*AttributeBinding `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanEvent) Reset() {
	*x = SpanEvent{}
	mi := &file_ir_v1_generation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanEvent) ProtoMessage() {}

func (x *SpanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanEvent.ProtoReflect.Descriptor instead.
func (*SpanEvent) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{11}
}

func (x *SpanEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpanEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpanEvent) GetStatuses() []RuntimeStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *SpanEvent) GetAttributes() []*AttributeBinding {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// PlanDiagnostic reports a generator-owned issue attached to a plan.
type PlanDiagnostic struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Severity PlanSeverity           `protobuf:"varint,1,opt,name=severity,proto3,enum=axiom.insight.ir.v1.PlanSeverity" json:"severity,omitempty"`
	// code is a stable generator diagnostic code, e.g. "GEN_NAME_COLLISION".
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// message never contains the dropped sensitive value itself.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanDiagnostic) Reset() {
	*x = PlanDiagnostic{}
	mi := &file_ir_v1_generation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDiagnostic) ProtoMessage() {}

func (x *PlanDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_generation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDiagnostic.ProtoReflect.Descriptor instead.
func (*PlanDiagnostic) Descriptor() ([]byte, []int) {
	return file_ir_v1_generation_proto_rawDescGZIP(), []int{12}
}

func (x *PlanDiagnostic) GetSeverity() PlanSeverity {
	if x != nil {
		return x.Severity
	}
	return PlanSeverity_PLAN_SEVERITY_UNSPECIFIED
}

func (x *PlanDiagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PlanDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ir_v1_generation_proto protoreflect.FileDescriptor

const file_ir_v1_generation_proto_rawDesc = "" +
	"\n" +
	"\x16ir/v1/generation.proto\x12\x13axiom.insight.ir.v1\"\xfc\x02\n" +
	"\x0eGenerationPlan\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x127\n" +
	"\x18source_ir_schema_version\x18\x02 \x01(\tR\x15sourceIrSchemaVersion\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x129\n" +
	"\ametrics\x18\x04 \x03(\v2\x1f.axiom.insight.ir.v1.MetricPlanR\ametrics\x123\n" +
	"\x05spans\x18\x05 \x03(\v2\x1d.axiom.insight.ir.v1.SpanPlanR\x05spans\x120\n" +
	"\x04logs\x18\x06 \x03(\v2\x1c.axiom.insight.ir.v1.LogPlanR\x04logs\x12E\n" +
	"\vdiagnostics\x18\a \x03(\v2#.axiom.insight.ir.v1.PlanDiagnosticR\vdiagnostics\"\xac\x03\n" +
	"\n" +
	"MetricPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1f.axiom.insight.ir.v1.MetricTypeR\x04type\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x126\n" +
	"\x06target\x18\x06 \x01(\v2\x1e.axiom.insight.ir.v1.TargetRefR\x06target\x126\n" +
	"\atrigger\x18\a \x01(\v2\x1c.axiom.insight.ir.v1.TriggerR\atrigger\x127\n" +
	"\x05value\x18\b \x01(\v2!.axiom.insight.ir.v1.ValueBindingR\x05value\x12E\n" +
	"\n" +
	"attributes\x18\t \x03(\v2%.axiom.insight.ir.v1.AttributeBindingR\n" +
	"attributes\x12\x1f\n" +
	"\vfunction_id\x18\n" +
	" \x01(\tR\n" +
	"functionId\"\x92\x04\n" +
	"\bSpanPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.axiom.insight.ir.v1.SpanKindR\x04kind\x126\n" +
	"\x06target\x18\x04 \x01(\v2\x1e.axiom.insight.ir.v1.TargetRefR\x06target\x12A\n" +
	"\rstart_trigger\x18\x05 \x01(\v2\x1c.axiom.insight.ir.v1.TriggerR\fstartTrigger\x12=\n" +
	"\vend_trigger\x18\x06 \x01(\v2\x1c.axiom.insight.ir.v1.TriggerR\n" +
	"endTrigger\x12;\n" +
	"\x06parent\x18\a \x01(\v2#.axiom.insight.ir.v1.ParentStrategyR\x06parent\x12E\n" +
	"\n" +
	"attributes\x18\b \x03(\v2%.axiom.insight.ir.v1.AttributeBindingR\n" +
	"attributes\x129\n" +
	"\x06status\x18\t \x01(\v2!.axiom.insight.ir.v1.StatusPolicyR\x06status\x126\n" +
	"\x06events\x18\n" +
	" \x03(\v2\x1e.axiom.insight.ir.v1.SpanEventR\x06events\"\x80\x03\n" +
	"\aLogPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12<\n" +
	"\bseverity\x18\x03 \x01(\x0e2 .axiom.insight.ir.v1.LogSeverityR\bseverity\x126\n" +
	"\x06target\x18\x04 \x01(\v2\x1e.axiom.insight.ir.v1.TargetRefR\x06target\x126\n" +
	"\atrigger\x18\x05 \x01(\v2\x1c.axiom.insight.ir.v1.TriggerR\atrigger\x129\n" +
	"\x06fields\x18\x06 \x03(\v2!.axiom.insight.ir.v1.FieldBindingR\x06fields\x12-\n" +
	"\x12correlation_fields\x18\a \x03(\tR\x11correlationFields\x12.\n" +
	"\x13redaction_policy_id\x18\b \x01(\tR\x11redactionPolicyId\"P\n" +
	"\tTargetRef\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.axiom.insight.ir.v1.TargetKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"B\n" +
	"\aTrigger\x127\n" +
	"\x05phase\x18\x01 \x01(\x0e2!.axiom.insight.ir.v1.TriggerPhaseR\x05phase\"\x91\x02\n" +
	"\fValueBinding\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x128\n" +
	"\x06source\x18\x02 \x01(\x0e2 .axiom.insight.ir.v1.ValueSourceR\x06source\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.axiom.insight.ir.v1.ValueTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1a\n" +
	"\bfallback\x18\x05 \x01(\tR\bfallback\x12G\n" +
	"\vcardinality\x18\x06 \x01(\x0e2%.axiom.insight.ir.v1.CardinalityClassR\vcardinality\"]\n" +
	"\x10AttributeBinding\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.axiom.insight.ir.v1.ValueBindingR\x05value\"Y\n" +
	"\fFieldBinding\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.axiom.insight.ir.v1.ValueBindingR\x05value\"\x80\x01\n" +
	"\x0eParentStrategy\x12;\n" +
	"\x04mode\x18\x01 \x01(\x0e2'.axiom.insight.ir.v1.ParentStrategyModeR\x04mode\x121\n" +
	"\x15static_parent_span_id\x18\x02 \x01(\tR\x12staticParentSpanId\"\xba\x02\n" +
	"\fStatusPolicy\x122\n" +
	"\x02ok\x18\x01 \x01(\x0e2\".axiom.insight.ir.v1.StatusSettingR\x02ok\x128\n" +
	"\x05error\x18\x02 \x01(\x0e2\".axiom.insight.ir.v1.StatusSettingR\x05error\x12<\n" +
	"\atimeout\x18\x03 \x01(\x0e2\".axiom.insight.ir.v1.StatusSettingR\atimeout\x12@\n" +
	"\tcancelled\x18\x04 \x01(\x0e2\".axiom.insight.ir.v1.StatusSettingR\tcancelled\x12<\n" +
	"\aunknown\x18\x05 \x01(\x0e2\".axiom.insight.ir.v1.StatusSettingR\aunknown\"\xb6\x01\n" +
	"\tSpanEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\bstatuses\x18\x03 \x03(\x0e2\".axiom.insight.ir.v1.RuntimeStatusR\bstatuses\x12E\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2%.axiom.insight.ir.v1.AttributeBindingR\n" +
	"attributes\"}\n" +
	"\x0ePlanDiagnostic\x12=\n" +
	"\bseverity\x18\x01 \x01(\x0e2!.axiom.insight.ir.v1.PlanSeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\x8d\x01\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_TYPE_COUNTER\x10\x01\x12\x19\n" +
	"\x15METRIC_TYPE_HISTOGRAM\x10\x02\x12\x15\n" +
	"\x11METRIC_TYPE_GAUGE\x10\x03\x12\x17\n" +
	"\x13METRIC_TYPE_SUMMARY\x10\x04*\x99\x01\n" +
	"\bSpanKind\x12\x19\n" +
	"\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SPAN_KIND_SERVER\x10\x01\x12\x14\n" +
	"\x10SPAN_KIND_CLIENT\x10\x02\x12\x16\n" +
	"\x12SPAN_KIND_PRODUCER\x10\x03\x12\x16\n" +
	"\x12SPAN_KIND_CONSUMER\x10\x04\x12\x16\n" +
	"\x12SPAN_KIND_INTERNAL\x10\x05*\x94\x01\n" +
	"\n" +
	"TargetKind\x12\x1b\n" +
	"\x17TARGET_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TARGET_KIND_ENDPOINT\x10\x01\x12\x18\n" +
	"\x14TARGET_KIND_FUNCTION\x10\x02\x12\x1a\n" +
	"\x16TARGET_KIND_DEPENDENCY\x10\x03\x12\x19\n" +
	"\x15TARGET_KIND_CALL_EDGE\x10\x04*}\n" +
	"\fTriggerPhase\x12\x1d\n" +
	"\x19TRIGGER_PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRIGGER_PHASE_START\x10\x01\x12\x15\n" +
	"\x11TRIGGER_PHASE_END\x10\x02\x12\x1e\n" +
	"\x1aTRIGGER_PHASE_STATE_CHANGE\x10\x03*\xcf\x01\n" +
	"\vValueSource\x12\x1c\n" +
	"\x18VALUE_SOURCE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVALUE_SOURCE_PLAN_CONSTANT\x10\x01\x12\x1c\n" +
	"\x18VALUE_SOURCE_IR_CONSTANT\x10\x02\x12!\n" +
	"\x1dVALUE_SOURCE_RUNTIME_RESOURCE\x10\x03\x12 \n" +
	"\x1cVALUE_SOURCE_RUNTIME_CONTEXT\x10\x04\x12\x1f\n" +
	"\x1bVALUE_SOURCE_RUNTIME_RESULT\x10\x05*\x97\x01\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VALUE_TYPE_STRING\x10\x01\x12\x14\n" +
	"\x10VALUE_TYPE_INT64\x10\x02\x12\x15\n" +
	"\x11VALUE_TYPE_DOUBLE\x10\x03\x12\x13\n" +
	"\x0fVALUE_TYPE_BOOL\x10\x04\x12\x15\n" +
	"\x11VALUE_TYPE_STATUS\x10\x05*\x8c\x01\n" +
	"\x10CardinalityClass\x12!\n" +
	"\x1dCARDINALITY_CLASS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCARDINALITY_CLASS_CONSTANT\x10\x01\x12\x19\n" +
	"\x15CARDINALITY_CLASS_LOW\x10\x02\x12\x1a\n" +
	"\x16CARDINALITY_CLASS_HIGH\x10\x03*\xd2\x01\n" +
	"\x12ParentStrategyMode\x12$\n" +
	" PARENT_STRATEGY_MODE_UNSPECIFIED\x10\x00\x12(\n" +
	"$PARENT_STRATEGY_MODE_EXTRACT_OR_ROOT\x10\x01\x12!\n" +
	"\x1dPARENT_STRATEGY_MODE_NEW_ROOT\x10\x02\x12(\n" +
	"$PARENT_STRATEGY_MODE_CURRENT_CONTEXT\x10\x03\x12\x1f\n" +
	"\x1bPARENT_STRATEGY_MODE_STATIC\x10\x04*z\n" +
	"\rStatusSetting\x12\x1e\n" +
	"\x1aSTATUS_SETTING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STATUS_SETTING_UNSET\x10\x01\x12\x18\n" +
	"\x14STATUS_SETTING_ERROR\x10\x02\x12\x15\n" +
	"\x11STATUS_SETTING_OK\x10\x03*\xb6\x01\n" +
	"\rRuntimeStatus\x12\x1e\n" +
	"\x1aRUNTIME_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUNTIME_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14RUNTIME_STATUS_ERROR\x10\x02\x12\x1c\n" +
	"\x18RUNTIME_STATUS_CANCELLED\x10\x03\x12\x1a\n" +
	"\x16RUNTIME_STATUS_TIMEOUT\x10\x04\x12\x1a\n" +
	"\x16RUNTIME_STATUS_UNKNOWN\x10\x05*q\n" +
	"\vLogSeverity\x12\x1c\n" +
	"\x18LOG_SEVERITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_SEVERITY_INFO\x10\x01\x12\x15\n" +
	"\x11LOG_SEVERITY_WARN\x10\x02\x12\x16\n" +
	"\x12LOG_SEVERITY_ERROR\x10\x03*y\n" +
	"\fPlanSeverity\x12\x1d\n" +
	"\x19PLAN_SEVERITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLAN_SEVERITY_INFO\x10\x01\x12\x19\n" +
	"\x15PLAN_SEVERITY_WARNING\x10\x02\x12\x17\n" +
	"\x13PLAN_SEVERITY_ERROR\x10\x03B9Z7github.com/zhuyanxi/axiom-insight/ir/v1;observabilityv1b\x06proto3"

var (
	file_ir_v1_generation_proto_rawDescOnce sync.Once
	file_ir_v1_generation_proto_rawDescData []byte
)

func file_ir_v1_generation_proto_rawDescGZIP() []byte {
	file_ir_v1_generation_proto_rawDescOnce.Do(func() {
		file_ir_v1_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ir_v1_generation_proto_rawDesc), len(file_ir_v1_generation_proto_rawDesc)))
	})
	return file_ir_v1_generation_proto_rawDescData
}

var file_ir_v1_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_ir_v1_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ir_v1_generation_proto_goTypes = []any{
	(MetricType)(0),          // 0: axiom.insight.ir.v1.MetricType
	(SpanKind)(0),            // 1: axiom.insight.ir.v1.SpanKind
	(TargetKind)(0),          // 2: axiom.insight.ir.v1.TargetKind
	(TriggerPhase)(0),        // 3: axiom.insight.ir.v1.TriggerPhase
	(ValueSource)(0),         // 4: axiom.insight.ir.v1.ValueSource
	(ValueType)(0),           // 5: axiom.insight.ir.v1.ValueType
	(CardinalityClass)(0),    // 6: axiom.insight.ir.v1.CardinalityClass
	(ParentStrategyMode)(0),  // 7: axiom.insight.ir.v1.ParentStrategyMode
	(StatusSetting)(0),       // 8: axiom.insight.ir.v1.StatusSetting
	(RuntimeStatus)(0),       // 9: axiom.insight.ir.v1.RuntimeStatus
	(LogSeverity)(0),         // 10: axiom.insight.ir.v1.LogSeverity
	(PlanSeverity)(0),        // 11: axiom.insight.ir.v1.PlanSeverity
	(*GenerationPlan)(nil),   // 12: axiom.insight.ir.v1.GenerationPlan
	(*MetricPlan)(nil),       // 13: axiom.insight.ir.v1.MetricPlan
	(*SpanPlan)(nil),         // 14: axiom.insight.ir.v1.SpanPlan
	(*LogPlan)(nil),          // 15: axiom.insight.ir.v1.LogPlan
	(*TargetRef)(nil),        // 16: axiom.insight.ir.v1.TargetRef
	(*Trigger)(nil),          // 17: axiom.insight.ir.v1.Trigger
	(*ValueBinding)(nil),     // 18: axiom.insight.ir.v1.ValueBinding
	(*AttributeBinding)(nil), // 19: axiom.insight.ir.v1.AttributeBinding
	(*FieldBinding)(nil),     // 20: axiom.insight.ir.v1.FieldBinding
	(*ParentStrategy)(nil),   // 21: axiom.insight.ir.v1.ParentStrategy
	(*StatusPolicy)(nil),     // 22: axiom.insight.ir.v1.StatusPolicy
	(*SpanEvent)(nil),        // 23: axiom.insight.ir.v1.SpanEvent
	(*PlanDiagnostic)(nil),   // 24: axiom.insight.ir.v1.PlanDiagnostic
}
var file_ir_v1_generation_proto_depIdxs = []int32{
	13, // 0: axiom.insight.ir.v1.GenerationPlan.metrics:type_name -> axiom.insight.ir.v1.MetricPlan
	14, // 1: axiom.insight.ir.v1.GenerationPlan.spans:type_name -> axiom.insight.ir.v1.SpanPlan
	15, // 2: axiom.insight.ir.v1.GenerationPlan.logs:type_name -> axiom.insight.ir.v1.LogPlan
	24, // 3: axiom.insight.ir.v1.GenerationPlan.diagnostics:type_name -> axiom.insight.ir.v1.PlanDiagnostic
	0,  // 4: axiom.insight.ir.v1.MetricPlan.type:type_name -> axiom.insight.ir.v1.MetricType
	16, // 5: axiom.insight.ir.v1.MetricPlan.target:type_name -> axiom.insight.ir.v1.TargetRef
	17, // 6: axiom.insight.ir.v1.MetricPlan.trigger:type_name -> axiom.insight.ir.v1.Trigger
	18, // 7: axiom.insight.ir.v1.MetricPlan.value:type_name -> axiom.insight.ir.v1.ValueBinding
	19, // 8: axiom.insight.ir.v1.MetricPlan.attributes:type_name -> axiom.insight.ir.v1.AttributeBinding
	1,  // 9: axiom.insight.ir.v1.SpanPlan.kind:type_name -> axiom.insight.ir.v1.SpanKind
	16, // 10: axiom.insight.ir.v1.SpanPlan.target:type_name -> axiom.insight.ir.v1.TargetRef
	17, // 11: axiom.insight.ir.v1.SpanPlan.start_trigger:type_name -> axiom.insight.ir.v1.Trigger
	17, // 12: axiom.insight.ir.v1.SpanPlan.end_trigger:type_name -> axiom.insight.ir.v1.Trigger
	21, // 13: axiom.insight.ir.v1.SpanPlan.parent:type_name -> axiom.insight.ir.v1.ParentStrategy
	19, // 14: axiom.insight.ir.v1.SpanPlan.attributes:type_name -> axiom.insight.ir.v1.AttributeBinding
	22, // 15: axiom.insight.ir.v1.SpanPlan.status:type_name -> axiom.insight.ir.v1.StatusPolicy
	23, // 16: axiom.insight.ir.v1.SpanPlan.events:type_name -> axiom.insight.ir.v1.SpanEvent
	10, // 17: axiom.insight.ir.v1.LogPlan.severity:type_name -> axiom.insight.ir.v1.LogSeverity
	16, // 18: axiom.insight.ir.v1.LogPlan.target:type_name -> axiom.insight.ir.v1.TargetRef
	17, // 19: axiom.insight.ir.v1.LogPlan.trigger:type_name -> axiom.insight.ir.v1.Trigger
	20, // 20: axiom.insight.ir.v1.LogPlan.fields:type_name -> axiom.insight.ir.v1.FieldBinding
	2,  // 21: axiom.insight.ir.v1.TargetRef.kind:type_name -> axiom.insight.ir.v1.TargetKind
	3,  // 22: axiom.insight.ir.v1.Trigger.phase:type_name -> axiom.insight.ir.v1.TriggerPhase
	4,  // 23: axiom.insight.ir.v1.ValueBinding.source:type_name -> axiom.insight.ir.v1.ValueSource
	5,  // 24: axiom.insight.ir.v1.ValueBinding.type:type_name -> axiom.insight.ir.v1.ValueType
	6,  // 25: axiom.insight.ir.v1.ValueBinding.cardinality:type_name -> axiom.insight.ir.v1.CardinalityClass
	18, // 26: axiom.insight.ir.v1.AttributeBinding.value:type_name -> axiom.insight.ir.v1.ValueBinding
	18, // 27: axiom.insight.ir.v1.FieldBinding.value:type_name -> axiom.insight.ir.v1.ValueBinding
	7,  // 28: axiom.insight.ir.v1.ParentStrategy.mode:type_name -> axiom.insight.ir.v1.ParentStrategyMode
	8,  // 29: axiom.insight.ir.v1.StatusPolicy.ok:type_name -> axiom.insight.ir.v1.StatusSetting
	8,  // 30: axiom.insight.ir.v1.StatusPolicy.error:type_name -> axiom.insight.ir.v1.StatusSetting
	8,  // 31: axiom.insight.ir.v1.StatusPolicy.timeout:type_name -> axiom.insight.ir.v1.StatusSetting
	8,  // 32: axiom.insight.ir.v1.StatusPolicy.cancelled:type_name -> axiom.insight.ir.v1.StatusSetting
	8,  // 33: axiom.insight.ir.v1.StatusPolicy.unknown:type_name -> axiom.insight.ir.v1.StatusSetting
	9,  // 34: axiom.insight.ir.v1.SpanEvent.statuses:type_name -> axiom.insight.ir.v1.RuntimeStatus
	19, // 35: axiom.insight.ir.v1.SpanEvent.attributes:type_name -> axiom.insight.ir.v1.AttributeBinding
	11, // 36: axiom.insight.ir.v1.PlanDiagnostic.severity:type_name -> axiom.insight.ir.v1.PlanSeverity
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_ir_v1_generation_proto_init() }
func file_ir_v1_generation_proto_init() {
	if File_ir_v1_generation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ir_v1_generation_proto_rawDesc), len(file_ir_v1_generation_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ir_v1_generation_proto_goTypes,
		DependencyIndexes: file_ir_v1_generation_proto_depIdxs,
		EnumInfos:         file_ir_v1_generation_proto_enumTypes,
		MessageInfos:      file_ir_v1_generation_proto_msgTypes,
	}.Build()
	File_ir_v1_generation_proto = out.File
	file_ir_v1_generation_proto_goTypes = nil
	file_ir_v1_generation_proto_depIdxs = nil
}
