// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: ir/v1/language_analyzer.proto

package observabilityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanguageAnalyzer_GetMetadata_FullMethodName = "/axiom.insight.ir.v1.LanguageAnalyzer/GetMetadata"
	LanguageAnalyzer_Analyze_FullMethodName     = "/axiom.insight.ir.v1.LanguageAnalyzer/Analyze"
)

// LanguageAnalyzerClient is the client API for LanguageAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LanguageAnalyzer exposes a language frontend through a stable protocol.
type LanguageAnalyzerClient interface {
	// GetMetadata performs optional schema-version handshake.
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*LanguageAnalyzerMetadata, error)
	// Analyze scans source and returns language-neutral IR.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type languageAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewLanguageAnalyzerClient(cc grpc.ClientConnInterface) LanguageAnalyzerClient {
	return &languageAnalyzerClient{cc}
}

func (c *languageAnalyzerClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*LanguageAnalyzerMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LanguageAnalyzerMetadata)
	err := c.cc.Invoke(ctx, LanguageAnalyzer_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *languageAnalyzerClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, LanguageAnalyzer_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanguageAnalyzerServer is the server API for LanguageAnalyzer service.
// All implementations must embed UnimplementedLanguageAnalyzerServer
// for forward compatibility.
//
// LanguageAnalyzer exposes a language frontend through a stable protocol.
type LanguageAnalyzerServer interface {
	// GetMetadata performs optional schema-version handshake.
	GetMetadata(context.Context, *GetMetadataRequest) (*LanguageAnalyzerMetadata, error)
	// Analyze scans source and returns language-neutral IR.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedLanguageAnalyzerServer()
}

// UnimplementedLanguageAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanguageAnalyzerServer struct{}

func (UnimplementedLanguageAnalyzerServer) GetMetadata(context.Context, *GetMetadataRequest) (*LanguageAnalyzerMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedLanguageAnalyzerServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedLanguageAnalyzerServer) mustEmbedUnimplementedLanguageAnalyzerServer() {}
func (UnimplementedLanguageAnalyzerServer) testEmbeddedByValue()                          {}

// UnsafeLanguageAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanguageAnalyzerServer will
// result in compilation errors.
type UnsafeLanguageAnalyzerServer interface {
	mustEmbedUnimplementedLanguageAnalyzerServer()
}

func RegisterLanguageAnalyzerServer(s grpc.ServiceRegistrar, srv LanguageAnalyzerServer) {
	// If the following call pancis, it indicates UnimplementedLanguageAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanguageAnalyzer_ServiceDesc, srv)
}

func _LanguageAnalyzer_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageAnalyzerServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageAnalyzer_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageAnalyzerServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanguageAnalyzer_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageAnalyzerServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageAnalyzer_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageAnalyzerServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanguageAnalyzer_ServiceDesc is the grpc.ServiceDesc for LanguageAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanguageAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axiom.insight.ir.v1.LanguageAnalyzer",
	HandlerType: (*LanguageAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _LanguageAnalyzer_GetMetadata_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _LanguageAnalyzer_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ir/v1/language_analyzer.proto",
}
