// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ir/v1/language_analyzer.proto

package observabilityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMetadataRequest optionally constrains the schema version requested by a client.
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_ir_v1_language_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetadataRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

// LanguageAnalyzerMetadata describes frontend capabilities and compatible IR versions.
type LanguageAnalyzerMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Language         string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	PluginVersion    string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Capabilities     []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MinSchemaVersion string                 `protobuf:"bytes,4,opt,name=min_schema_version,json=minSchemaVersion,proto3" json:"min_schema_version,omitempty"`
	MaxSchemaVersion string                 `protobuf:"bytes,5,opt,name=max_schema_version,json=maxSchemaVersion,proto3" json:"max_schema_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LanguageAnalyzerMetadata) Reset() {
	*x = LanguageAnalyzerMetadata{}
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageAnalyzerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageAnalyzerMetadata) ProtoMessage() {}

func (x *LanguageAnalyzerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageAnalyzerMetadata.ProtoReflect.Descriptor instead.
func (*LanguageAnalyzerMetadata) Descriptor() ([]byte, []int) {
	return file_ir_v1_language_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *LanguageAnalyzerMetadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LanguageAnalyzerMetadata) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *LanguageAnalyzerMetadata) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *LanguageAnalyzerMetadata) GetMinSchemaVersion() string {
	if x != nil {
		return x.MinSchemaVersion
	}
	return ""
}

func (x *LanguageAnalyzerMetadata) GetMaxSchemaVersion() string {
	if x != nil {
		return x.MaxSchemaVersion
	}
	return ""
}

// AnalyzeRequest contains offline source-scan inputs.
type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRoot    string                 `protobuf:"bytes,1,opt,name=source_root,json=sourceRoot,proto3" json:"source_root,omitempty"`
	Include       []string               `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	IncludeTests  bool                   `protobuf:"varint,6,opt,name=include_tests,json=includeTests,proto3" json:"include_tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_ir_v1_language_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeRequest) GetSourceRoot() string {
	if x != nil {
		return x.SourceRoot
	}
	return ""
}

func (x *AnalyzeRequest) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *AnalyzeRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *AnalyzeRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *AnalyzeRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AnalyzeRequest) GetIncludeTests() bool {
	if x != nil {
		return x.IncludeTests
	}
	return false
}

// AnalyzeResponse contains IR and diagnostics produced by frontend.
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *ObservabilityDocument `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_language_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_ir_v1_language_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeResponse) GetDocument() *ObservabilityDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *AnalyzeResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

var File_ir_v1_language_analyzer_proto protoreflect.FileDescriptor

const file_ir_v1_language_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x1dir/v1/language_analyzer.proto\x12\x13axiom.insight.ir.v1\x1a\x19ir/v1/observability.proto\";\n" +
	"\x12GetMetadataRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\"\xdd\x01\n" +
	"\x18LanguageAnalyzerMetadata\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12,\n" +
	"\x12min_schema_version\x18\x04 \x01(\tR\x10minSchemaVersion\x12,\n" +
	"\x12max_schema_version\x18\x05 \x01(\tR\x10maxSchemaVersion\"\xc9\x01\n" +
	"\x0eAnalyzeRequest\x12\x1f\n" +
	"\vsource_root\x18\x01 \x01(\tR\n" +
	"sourceRoot\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\tR\rschemaVersion\x12#\n" +
	"\rinclude_tests\x18\x06 \x01(\bR\fincludeTests\"\x9c\x01\n" +
	"\x0fAnalyzeResponse\x12F\n" +
	"\bdocument\x18\x01 \x01(\v2*.axiom.insight.ir.v1.ObservabilityDocumentR\bdocument\x12A\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1f.axiom.insight.ir.v1.DiagnosticR\vdiagnostics2\xcf\x01\n" +
	"\x10LanguageAnalyzer\x12e\n" +
	"\vGetMetadata\x12'.axiom.insight.ir.v1.GetMetadataRequest\x1a-.axiom.insight.ir.v1.LanguageAnalyzerMetadata\x12T\n" +
	"\aAnalyze\x12#.axiom.insight.ir.v1.AnalyzeRequest\x1a$.axiom.insight.ir.v1.AnalyzeResponseB9Z7github.com/zhuyanxi/axiom-insight/ir/v1;observabilityv1b\x06proto3"

var (
	file_ir_v1_language_analyzer_proto_rawDescOnce sync.Once
	file_ir_v1_language_analyzer_proto_rawDescData []byte
)

func file_ir_v1_language_analyzer_proto_rawDescGZIP() []byte {
	file_ir_v1_language_analyzer_proto_rawDescOnce.Do(func() {
		file_ir_v1_language_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ir_v1_language_analyzer_proto_rawDesc), len(file_ir_v1_language_analyzer_proto_rawDesc)))
	})
	return file_ir_v1_language_analyzer_proto_rawDescData
}

var file_ir_v1_language_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ir_v1_language_analyzer_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),       // 0: axiom.insight.ir.v1.GetMetadataRequest
	(*LanguageAnalyzerMetadata)(nil), // 1: axiom.insight.ir.v1.LanguageAnalyzerMetadata
	(*AnalyzeRequest)(nil),           // 2: axiom.insight.ir.v1.AnalyzeRequest
	(*AnalyzeResponse)(nil),          // 3: axiom.insight.ir.v1.AnalyzeResponse
	(*ObservabilityDocument)(nil),    // 4: axiom.insight.ir.v1.ObservabilityDocument
	(*Diagnostic)(nil),               // 5: axiom.insight.ir.v1.Diagnostic
}
var file_ir_v1_language_analyzer_proto_depIdxs = []int32{
	4, // 0: axiom.insight.ir.v1.AnalyzeResponse.document:type_name -> axiom.insight.ir.v1.ObservabilityDocument
	5, // 1: axiom.insight.ir.v1.AnalyzeResponse.diagnostics:type_name -> axiom.insight.ir.v1.Diagnostic
	0, // 2: axiom.insight.ir.v1.LanguageAnalyzer.GetMetadata:input_type -> axiom.insight.ir.v1.GetMetadataRequest
	2, // 3: axiom.insight.ir.v1.LanguageAnalyzer.Analyze:input_type -> axiom.insight.ir.v1.AnalyzeRequest
	1, // 4: axiom.insight.ir.v1.LanguageAnalyzer.GetMetadata:output_type -> axiom.insight.ir.v1.LanguageAnalyzerMetadata
	3, // 5: axiom.insight.ir.v1.LanguageAnalyzer.Analyze:output_type -> axiom.insight.ir.v1.AnalyzeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ir_v1_language_analyzer_proto_init() }
func file_ir_v1_language_analyzer_proto_init() {
	if File_ir_v1_language_analyzer_proto != nil {
		return
	}
	file_ir_v1_observability_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ir_v1_language_analyzer_proto_rawDesc), len(file_ir_v1_language_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ir_v1_language_analyzer_proto_goTypes,
		DependencyIndexes: file_ir_v1_language_analyzer_proto_depIdxs,
		MessageInfos:      file_ir_v1_language_analyzer_proto_msgTypes,
	}.Build()
	File_ir_v1_language_analyzer_proto = out.File
	file_ir_v1_language_analyzer_proto_goTypes = nil
	file_ir_v1_language_analyzer_proto_depIdxs = nil
}
