// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ir/v1/observability.proto

package observabilityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointKind identifies supported service entrypoint categories.
type EndpointKind int32

const (
	EndpointKind_ENDPOINT_KIND_UNSPECIFIED EndpointKind = 0
	EndpointKind_HTTP_HANDLER              EndpointKind = 1
	EndpointKind_GRPC_HANDLER              EndpointKind = 2
	EndpointKind_CRON_JOB                  EndpointKind = 3
)

// Enum value maps for EndpointKind.
var (
	EndpointKind_name = map[int32]string{
		0: "ENDPOINT_KIND_UNSPECIFIED",
		1: "HTTP_HANDLER",
		2: "GRPC_HANDLER",
		3: "CRON_JOB",
	}
	EndpointKind_value = map[string]int32{
		"ENDPOINT_KIND_UNSPECIFIED": 0,
		"HTTP_HANDLER":              1,
		"GRPC_HANDLER":              2,
		"CRON_JOB":                  3,
	}
)

func (x EndpointKind) Enum() *EndpointKind {
	p := new(EndpointKind)
	*p = x
	return p
}

func (x EndpointKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_observability_proto_enumTypes[0].Descriptor()
}

func (EndpointKind) Type() protoreflect.EnumType {
	return &file_ir_v1_observability_proto_enumTypes[0]
}

func (x EndpointKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointKind.Descriptor instead.
func (EndpointKind) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{0}
}

// DependencyKind identifies supported external dependency categories.
type DependencyKind int32

const (
	DependencyKind_DEPENDENCY_KIND_UNSPECIFIED DependencyKind = 0
	DependencyKind_KAFKA_PRODUCER              DependencyKind = 1
	DependencyKind_KAFKA_CONSUMER              DependencyKind = 2
	DependencyKind_SQL                         DependencyKind = 3
	DependencyKind_REDIS                       DependencyKind = 4
	DependencyKind_HTTP_CLIENT                 DependencyKind = 5
	DependencyKind_RPC_CLIENT                  DependencyKind = 6
)

// Enum value maps for DependencyKind.
var (
	DependencyKind_name = map[int32]string{
		0: "DEPENDENCY_KIND_UNSPECIFIED",
		1: "KAFKA_PRODUCER",
		2: "KAFKA_CONSUMER",
		3: "SQL",
		4: "REDIS",
		5: "HTTP_CLIENT",
		6: "RPC_CLIENT",
	}
	DependencyKind_value = map[string]int32{
		"DEPENDENCY_KIND_UNSPECIFIED": 0,
		"KAFKA_PRODUCER":              1,
		"KAFKA_CONSUMER":              2,
		"SQL":                         3,
		"REDIS":                       4,
		"HTTP_CLIENT":                 5,
		"RPC_CLIENT":                  6,
	}
)

func (x DependencyKind) Enum() *DependencyKind {
	p := new(DependencyKind)
	*p = x
	return p
}

func (x DependencyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_observability_proto_enumTypes[1].Descriptor()
}

func (DependencyKind) Type() protoreflect.EnumType {
	return &file_ir_v1_observability_proto_enumTypes[1]
}

func (x DependencyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyKind.Descriptor instead.
func (DependencyKind) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{1}
}

// CallResolution describes whether a call target was statically resolved.
type CallResolution int32

const (
	CallResolution_CALL_RESOLUTION_UNSPECIFIED CallResolution = 0
	CallResolution_RESOLVED                    CallResolution = 1
	CallResolution_UNRESOLVED                  CallResolution = 2
)

// Enum value maps for CallResolution.
var (
	CallResolution_name = map[int32]string{
		0: "CALL_RESOLUTION_UNSPECIFIED",
		1: "RESOLVED",
		2: "UNRESOLVED",
	}
	CallResolution_value = map[string]int32{
		"CALL_RESOLUTION_UNSPECIFIED": 0,
		"RESOLVED":                    1,
		"UNRESOLVED":                  2,
	}
)

func (x CallResolution) Enum() *CallResolution {
	p := new(CallResolution)
	*p = x
	return p
}

func (x CallResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_observability_proto_enumTypes[2].Descriptor()
}

func (CallResolution) Type() protoreflect.EnumType {
	return &file_ir_v1_observability_proto_enumTypes[2]
}

func (x CallResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallResolution.Descriptor instead.
func (CallResolution) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{2}
}

// DiagnosticSeverity controls how an analysis diagnostic is presented.
type DiagnosticSeverity int32

const (
	DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED DiagnosticSeverity = 0
	DiagnosticSeverity_INFO                            DiagnosticSeverity = 1
	DiagnosticSeverity_WARNING                         DiagnosticSeverity = 2
	DiagnosticSeverity_ERROR                           DiagnosticSeverity = 3
)

// Enum value maps for DiagnosticSeverity.
var (
	DiagnosticSeverity_name = map[int32]string{
		0: "DIAGNOSTIC_SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	DiagnosticSeverity_value = map[string]int32{
		"DIAGNOSTIC_SEVERITY_UNSPECIFIED": 0,
		"INFO":                            1,
		"WARNING":                         2,
		"ERROR":                           3,
	}
)

func (x DiagnosticSeverity) Enum() *DiagnosticSeverity {
	p := new(DiagnosticSeverity)
	*p = x
	return p
}

func (x DiagnosticSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_ir_v1_observability_proto_enumTypes[3].Descriptor()
}

func (DiagnosticSeverity) Type() protoreflect.EnumType {
	return &file_ir_v1_observability_proto_enumTypes[3]
}

func (x DiagnosticSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticSeverity.Descriptor instead.
func (DiagnosticSeverity) EnumDescriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{3}
}

// ObservabilityDocument is the language-neutral compiler output.
type ObservabilityDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Service       *Service               `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Packages      []*Package             `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	Functions     []*Function            `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Dependencies  []*Dependency          `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	CallEdges     []*CallEdge            `protobuf:"bytes,7,rep,name=call_edges,json=callEdges,proto3" json:"call_edges,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,8,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservabilityDocument) Reset() {
	*x = ObservabilityDocument{}
	mi := &file_ir_v1_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservabilityDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservabilityDocument) ProtoMessage() {}

func (x *ObservabilityDocument) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservabilityDocument.ProtoReflect.Descriptor instead.
func (*ObservabilityDocument) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{0}
}

func (x *ObservabilityDocument) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ObservabilityDocument) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ObservabilityDocument) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ObservabilityDocument) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *ObservabilityDocument) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ObservabilityDocument) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ObservabilityDocument) GetCallEdges() []*CallEdge {
	if x != nil {
		return x.CallEdges
	}
	return nil
}

func (x *ObservabilityDocument) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Service identifies analyzed source and its language frontend.
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceRoot    string                 `protobuf:"bytes,2,opt,name=source_root,json=sourceRoot,proto3" json:"source_root,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	ModulePath    string                 `protobuf:"bytes,4,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	PackageIds    []string               `protobuf:"bytes,6,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_ir_v1_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetSourceRoot() string {
	if x != nil {
		return x.SourceRoot
	}
	return ""
}

func (x *Service) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Service) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Service) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

// Package describes one analyzed source package.
type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImportPath    string                 `protobuf:"bytes,3,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	Files         []string               `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_ir_v1_observability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

func (x *Package) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

// Function describes a source function and its statically known relationships.
type Function struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	QualifiedName     string                 `protobuf:"bytes,3,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	PackageId         string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackagePath       string                 `protobuf:"bytes,5,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	Receiver          string                 `protobuf:"bytes,6,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Signature         string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	SourceLocation    *SourceLocation        `protobuf:"bytes,8,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	Exported          bool                   `protobuf:"varint,9,opt,name=exported,proto3" json:"exported,omitempty"`
	InputEndpointIds  []string               `protobuf:"bytes,10,rep,name=input_endpoint_ids,json=inputEndpointIds,proto3" json:"input_endpoint_ids,omitempty"`
	OutputEndpointIds []string               `protobuf:"bytes,11,rep,name=output_endpoint_ids,json=outputEndpointIds,proto3" json:"output_endpoint_ids,omitempty"`
	DependencyIds     []string               `protobuf:"bytes,12,rep,name=dependency_ids,json=dependencyIds,proto3" json:"dependency_ids,omitempty"`
	CallerFunctionIds []string               `protobuf:"bytes,13,rep,name=caller_function_ids,json=callerFunctionIds,proto3" json:"caller_function_ids,omitempty"`
	CalleeFunctionIds []string               `protobuf:"bytes,14,rep,name=callee_function_ids,json=calleeFunctionIds,proto3" json:"callee_function_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_ir_v1_observability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{3}
}

func (x *Function) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Function) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Function) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *Function) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Function) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Function) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *Function) GetExported() bool {
	if x != nil {
		return x.Exported
	}
	return false
}

func (x *Function) GetInputEndpointIds() []string {
	if x != nil {
		return x.InputEndpointIds
	}
	return nil
}

func (x *Function) GetOutputEndpointIds() []string {
	if x != nil {
		return x.OutputEndpointIds
	}
	return nil
}

func (x *Function) GetDependencyIds() []string {
	if x != nil {
		return x.DependencyIds
	}
	return nil
}

func (x *Function) GetCallerFunctionIds() []string {
	if x != nil {
		return x.CallerFunctionIds
	}
	return nil
}

func (x *Function) GetCalleeFunctionIds() []string {
	if x != nil {
		return x.CalleeFunctionIds
	}
	return nil
}

// Endpoint describes a service entrypoint registered by source code.
type Endpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           EndpointKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=axiom.insight.ir.v1.EndpointKind" json:"kind,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FunctionId     string                 `protobuf:"bytes,4,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	SourceLocation *SourceLocation        `protobuf:"bytes,5,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	HttpMethod     string                 `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	HttpPath       string                 `protobuf:"bytes,7,opt,name=http_path,json=httpPath,proto3" json:"http_path,omitempty"`
	GrpcService    string                 `protobuf:"bytes,8,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	GrpcMethod     string                 `protobuf:"bytes,9,opt,name=grpc_method,json=grpcMethod,proto3" json:"grpc_method,omitempty"`
	CronSchedule   string                 `protobuf:"bytes,10,opt,name=cron_schedule,json=cronSchedule,proto3" json:"cron_schedule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_ir_v1_observability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{4}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetKind() EndpointKind {
	if x != nil {
		return x.Kind
	}
	return EndpointKind_ENDPOINT_KIND_UNSPECIFIED
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Endpoint) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *Endpoint) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *Endpoint) GetHttpPath() string {
	if x != nil {
		return x.HttpPath
	}
	return ""
}

func (x *Endpoint) GetGrpcService() string {
	if x != nil {
		return x.GrpcService
	}
	return ""
}

func (x *Endpoint) GetGrpcMethod() string {
	if x != nil {
		return x.GrpcMethod
	}
	return ""
}

func (x *Endpoint) GetCronSchedule() string {
	if x != nil {
		return x.CronSchedule
	}
	return ""
}

// Dependency describes an external system or client used by a function.
type Dependency struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           DependencyKind         `protobuf:"varint,2,opt,name=kind,proto3,enum=axiom.insight.ir.v1.DependencyKind" json:"kind,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FunctionId     string                 `protobuf:"bytes,4,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	SourceLocation *SourceLocation        `protobuf:"bytes,5,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	Operation      string                 `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	TargetService  string                 `protobuf:"bytes,7,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	TargetUrl      string                 `protobuf:"bytes,8,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	TargetPackage  string                 `protobuf:"bytes,9,opt,name=target_package,json=targetPackage,proto3" json:"target_package,omitempty"`
	Resource       string                 `protobuf:"bytes,10,opt,name=resource,proto3" json:"resource,omitempty"`
	Value          string                 `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	ValueIsStatic  bool                   `protobuf:"varint,12,opt,name=value_is_static,json=valueIsStatic,proto3" json:"value_is_static,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_ir_v1_observability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{5}
}

func (x *Dependency) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dependency) GetKind() DependencyKind {
	if x != nil {
		return x.Kind
	}
	return DependencyKind_DEPENDENCY_KIND_UNSPECIFIED
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *Dependency) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *Dependency) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Dependency) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *Dependency) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *Dependency) GetTargetPackage() string {
	if x != nil {
		return x.TargetPackage
	}
	return ""
}

func (x *Dependency) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Dependency) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Dependency) GetValueIsStatic() bool {
	if x != nil {
		return x.ValueIsStatic
	}
	return false
}

// CallEdge describes one statically analyzed function call.
type CallEdge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CallerFunctionId string                 `protobuf:"bytes,2,opt,name=caller_function_id,json=callerFunctionId,proto3" json:"caller_function_id,omitempty"`
	CalleeFunctionId string                 `protobuf:"bytes,3,opt,name=callee_function_id,json=calleeFunctionId,proto3" json:"callee_function_id,omitempty"`
	SourceLocation   *SourceLocation        `protobuf:"bytes,4,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	Resolution       CallResolution         `protobuf:"varint,5,opt,name=resolution,proto3,enum=axiom.insight.ir.v1.CallResolution" json:"resolution,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallEdge) Reset() {
	*x = CallEdge{}
	mi := &file_ir_v1_observability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEdge) ProtoMessage() {}

func (x *CallEdge) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEdge.ProtoReflect.Descriptor instead.
func (*CallEdge) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{6}
}

func (x *CallEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallEdge) GetCallerFunctionId() string {
	if x != nil {
		return x.CallerFunctionId
	}
	return ""
}

func (x *CallEdge) GetCalleeFunctionId() string {
	if x != nil {
		return x.CalleeFunctionId
	}
	return ""
}

func (x *CallEdge) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *CallEdge) GetResolution() CallResolution {
	if x != nil {
		return x.Resolution
	}
	return CallResolution_CALL_RESOLUTION_UNSPECIFIED
}

// Diagnostic preserves analysis information that needs user attention.
type Diagnostic struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       DiagnosticSeverity     `protobuf:"varint,1,opt,name=severity,proto3,enum=axiom.insight.ir.v1.DiagnosticSeverity" json:"severity,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SourceLocation *SourceLocation        `protobuf:"bytes,4,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_ir_v1_observability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{7}
}

func (x *Diagnostic) GetSeverity() DiagnosticSeverity {
	if x != nil {
		return x.Severity
	}
	return DiagnosticSeverity_DIAGNOSTIC_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

// SourceLocation is relative to the scan source root.
type SourceLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	StartLine     int32                  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartColumn   int32                  `protobuf:"varint,3,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndLine       int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     int32                  `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_ir_v1_observability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ir_v1_observability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_ir_v1_observability_proto_rawDescGZIP(), []int{8}
}

func (x *SourceLocation) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *SourceLocation) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *SourceLocation) GetStartColumn() int32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *SourceLocation) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *SourceLocation) GetEndColumn() int32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

var File_ir_v1_observability_proto protoreflect.FileDescriptor

const file_ir_v1_observability_proto_rawDesc = "" +
	"\n" +
	"\x19ir/v1/observability.proto\x12\x13axiom.insight.ir.v1\"\xf0\x03\n" +
	"\x15ObservabilityDocument\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x126\n" +
	"\aservice\x18\x02 \x01(\v2\x1c.axiom.insight.ir.v1.ServiceR\aservice\x128\n" +
	"\bpackages\x18\x03 \x03(\v2\x1c.axiom.insight.ir.v1.PackageR\bpackages\x12;\n" +
	"\tfunctions\x18\x04 \x03(\v2\x1d.axiom.insight.ir.v1.FunctionR\tfunctions\x12;\n" +
	"\tendpoints\x18\x05 \x03(\v2\x1d.axiom.insight.ir.v1.EndpointR\tendpoints\x12C\n" +
	"\fdependencies\x18\x06 \x03(\v2\x1f.axiom.insight.ir.v1.DependencyR\fdependencies\x12<\n" +
	"\n" +
	"call_edges\x18\a \x03(\v2\x1d.axiom.insight.ir.v1.CallEdgeR\tcallEdges\x12A\n" +
	"\vdiagnostics\x18\b \x03(\v2\x1f.axiom.insight.ir.v1.DiagnosticR\vdiagnostics\"\xb6\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_root\x18\x02 \x01(\tR\n" +
	"sourceRoot\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1f\n" +
	"\vmodule_path\x18\x04 \x01(\tR\n" +
	"modulePath\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1f\n" +
	"\vpackage_ids\x18\x06 \x03(\tR\n" +
	"packageIds\"d\n" +
	"\aPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vimport_path\x18\x03 \x01(\tR\n" +
	"importPath\x12\x14\n" +
	"\x05files\x18\x04 \x03(\tR\x05files\"\xa0\x04\n" +
	"\bFunction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x03 \x01(\tR\rqualifiedName\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\x12!\n" +
	"\fpackage_path\x18\x05 \x01(\tR\vpackagePath\x12\x1a\n" +
	"\breceiver\x18\x06 \x01(\tR\breceiver\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12L\n" +
	"\x0fsource_location\x18\b \x01(\v2#.axiom.insight.ir.v1.SourceLocationR\x0esourceLocation\x12\x1a\n" +
	"\bexported\x18\t \x01(\bR\bexported\x12,\n" +
	"\x12input_endpoint_ids\x18\n" +
	" \x03(\tR\x10inputEndpointIds\x12.\n" +
	"\x13output_endpoint_ids\x18\v \x03(\tR\x11outputEndpointIds\x12%\n" +
	"\x0edependency_ids\x18\f \x03(\tR\rdependencyIds\x12.\n" +
	"\x13caller_function_ids\x18\r \x03(\tR\x11callerFunctionIds\x12.\n" +
	"\x13callee_function_ids\x18\x0e \x03(\tR\x11calleeFunctionIds\"\xfb\x02\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.axiom.insight.ir.v1.EndpointKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vfunction_id\x18\x04 \x01(\tR\n" +
	"functionId\x12L\n" +
	"\x0fsource_location\x18\x05 \x01(\v2#.axiom.insight.ir.v1.SourceLocationR\x0esourceLocation\x12\x1f\n" +
	"\vhttp_method\x18\x06 \x01(\tR\n" +
	"httpMethod\x12\x1b\n" +
	"\thttp_path\x18\a \x01(\tR\bhttpPath\x12!\n" +
	"\fgrpc_service\x18\b \x01(\tR\vgrpcService\x12\x1f\n" +
	"\vgrpc_method\x18\t \x01(\tR\n" +
	"grpcMethod\x12#\n" +
	"\rcron_schedule\x18\n" +
	" \x01(\tR\fcronSchedule\"\xbd\x03\n" +
	"\n" +
	"Dependency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04kind\x18\x02 \x01(\x0e2#.axiom.insight.ir.v1.DependencyKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vfunction_id\x18\x04 \x01(\tR\n" +
	"functionId\x12L\n" +
	"\x0fsource_location\x18\x05 \x01(\v2#.axiom.insight.ir.v1.SourceLocationR\x0esourceLocation\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\x12%\n" +
	"\x0etarget_service\x18\a \x01(\tR\rtargetService\x12\x1d\n" +
	"\n" +
	"target_url\x18\b \x01(\tR\ttargetUrl\x12%\n" +
	"\x0etarget_package\x18\t \x01(\tR\rtargetPackage\x12\x1a\n" +
	"\bresource\x18\n" +
	" \x01(\tR\bresource\x12\x14\n" +
	"\x05value\x18\v \x01(\tR\x05value\x12&\n" +
	"\x0fvalue_is_static\x18\f \x01(\bR\rvalueIsStatic\"\x89\x02\n" +
	"\bCallEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12caller_function_id\x18\x02 \x01(\tR\x10callerFunctionId\x12,\n" +
	"\x12callee_function_id\x18\x03 \x01(\tR\x10calleeFunctionId\x12L\n" +
	"\x0fsource_location\x18\x04 \x01(\v2#.axiom.insight.ir.v1.SourceLocationR\x0esourceLocation\x12C\n" +
	"\n" +
	"resolution\x18\x05 \x01(\x0e2#.axiom.insight.ir.v1.CallResolutionR\n" +
	"resolution\"\xcd\x01\n" +
	"\n" +
	"Diagnostic\x12C\n" +
	"\bseverity\x18\x01 \x01(\x0e2'.axiom.insight.ir.v1.DiagnosticSeverityR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12L\n" +
	"\x0fsource_location\x18\x04 \x01(\v2#.axiom.insight.ir.v1.SourceLocationR\x0esourceLocation\"\xb1\x01\n" +
	"\x0eSourceLocation\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\x05R\tstartLine\x12!\n" +
	"\fstart_column\x18\x03 \x01(\x05R\vstartColumn\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x05 \x01(\x05R\tendColumn*_\n" +
	"\fEndpointKind\x12\x1d\n" +
	"\x19ENDPOINT_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fHTTP_HANDLER\x10\x01\x12\x10\n" +
	"\fGRPC_HANDLER\x10\x02\x12\f\n" +
	"\bCRON_JOB\x10\x03*\x8e\x01\n" +
	"\x0eDependencyKind\x12\x1f\n" +
	"\x1bDEPENDENCY_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKAFKA_PRODUCER\x10\x01\x12\x12\n" +
	"\x0eKAFKA_CONSUMER\x10\x02\x12\a\n" +
	"\x03SQL\x10\x03\x12\t\n" +
	"\x05REDIS\x10\x04\x12\x0f\n" +
	"\vHTTP_CLIENT\x10\x05\x12\x0e\n" +
	"\n" +
	"RPC_CLIENT\x10\x06*O\n" +
	"\x0eCallResolution\x12\x1f\n" +
	"\x1bCALL_RESOLUTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bRESOLVED\x10\x01\x12\x0e\n" +
	"\n" +
	"UNRESOLVED\x10\x02*[\n" +
	"\x12DiagnosticSeverity\x12#\n" +
	"\x1fDIAGNOSTIC_SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B7Z5github.com/pingli/axiom-insight/ir/v1;observabilityv1b\x06proto3"

var (
	file_ir_v1_observability_proto_rawDescOnce sync.Once
	file_ir_v1_observability_proto_rawDescData []byte
)

func file_ir_v1_observability_proto_rawDescGZIP() []byte {
	file_ir_v1_observability_proto_rawDescOnce.Do(func() {
		file_ir_v1_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ir_v1_observability_proto_rawDesc), len(file_ir_v1_observability_proto_rawDesc)))
	})
	return file_ir_v1_observability_proto_rawDescData
}

var file_ir_v1_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ir_v1_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ir_v1_observability_proto_goTypes = []any{
	(EndpointKind)(0),             // 0: axiom.insight.ir.v1.EndpointKind
	(DependencyKind)(0),           // 1: axiom.insight.ir.v1.DependencyKind
	(CallResolution)(0),           // 2: axiom.insight.ir.v1.CallResolution
	(DiagnosticSeverity)(0),       // 3: axiom.insight.ir.v1.DiagnosticSeverity
	(*ObservabilityDocument)(nil), // 4: axiom.insight.ir.v1.ObservabilityDocument
	(*Service)(nil),               // 5: axiom.insight.ir.v1.Service
	(*Package)(nil),               // 6: axiom.insight.ir.v1.Package
	(*Function)(nil),              // 7: axiom.insight.ir.v1.Function
	(*Endpoint)(nil),              // 8: axiom.insight.ir.v1.Endpoint
	(*Dependency)(nil),            // 9: axiom.insight.ir.v1.Dependency
	(*CallEdge)(nil),              // 10: axiom.insight.ir.v1.CallEdge
	(*Diagnostic)(nil),            // 11: axiom.insight.ir.v1.Diagnostic
	(*SourceLocation)(nil),        // 12: axiom.insight.ir.v1.SourceLocation
}
var file_ir_v1_observability_proto_depIdxs = []int32{
	5,  // 0: axiom.insight.ir.v1.ObservabilityDocument.service:type_name -> axiom.insight.ir.v1.Service
	6,  // 1: axiom.insight.ir.v1.ObservabilityDocument.packages:type_name -> axiom.insight.ir.v1.Package
	7,  // 2: axiom.insight.ir.v1.ObservabilityDocument.functions:type_name -> axiom.insight.ir.v1.Function
	8,  // 3: axiom.insight.ir.v1.ObservabilityDocument.endpoints:type_name -> axiom.insight.ir.v1.Endpoint
	9,  // 4: axiom.insight.ir.v1.ObservabilityDocument.dependencies:type_name -> axiom.insight.ir.v1.Dependency
	10, // 5: axiom.insight.ir.v1.ObservabilityDocument.call_edges:type_name -> axiom.insight.ir.v1.CallEdge
	11, // 6: axiom.insight.ir.v1.ObservabilityDocument.diagnostics:type_name -> axiom.insight.ir.v1.Diagnostic
	12, // 7: axiom.insight.ir.v1.Function.source_location:type_name -> axiom.insight.ir.v1.SourceLocation
	0,  // 8: axiom.insight.ir.v1.Endpoint.kind:type_name -> axiom.insight.ir.v1.EndpointKind
	12, // 9: axiom.insight.ir.v1.Endpoint.source_location:type_name -> axiom.insight.ir.v1.SourceLocation
	1,  // 10: axiom.insight.ir.v1.Dependency.kind:type_name -> axiom.insight.ir.v1.DependencyKind
	12, // 11: axiom.insight.ir.v1.Dependency.source_location:type_name -> axiom.insight.ir.v1.SourceLocation
	12, // 12: axiom.insight.ir.v1.CallEdge.source_location:type_name -> axiom.insight.ir.v1.SourceLocation
	2,  // 13: axiom.insight.ir.v1.CallEdge.resolution:type_name -> axiom.insight.ir.v1.CallResolution
	3,  // 14: axiom.insight.ir.v1.Diagnostic.severity:type_name -> axiom.insight.ir.v1.DiagnosticSeverity
	12, // 15: axiom.insight.ir.v1.Diagnostic.source_location:type_name -> axiom.insight.ir.v1.SourceLocation
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ir_v1_observability_proto_init() }
func file_ir_v1_observability_proto_init() {
	if File_ir_v1_observability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ir_v1_observability_proto_rawDesc), len(file_ir_v1_observability_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ir_v1_observability_proto_goTypes,
		DependencyIndexes: file_ir_v1_observability_proto_depIdxs,
		EnumInfos:         file_ir_v1_observability_proto_enumTypes,
		MessageInfos:      file_ir_v1_observability_proto_msgTypes,
	}.Build()
	File_ir_v1_observability_proto = out.File
	file_ir_v1_observability_proto_goTypes = nil
	file_ir_v1_observability_proto_depIdxs = nil
}
